package models

import (
	"time"

	"github.com/google/uuid"
)

type Incident struct {
	ID            uuid.UUID  `json:"id"`
	OrgID         uuid.UUID  `json:"org_id"`
	Title         string     `json:"title"`
	Status        string     `json:"status"`
	Severity      string     `json:"severity"`
	AutoGenerated bool       `json:"auto_generated"`
	StartedAt     time.Time  `json:"started_at"`
	ResolvedAt    *time.Time `json:"resolved_at,omitempty"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
}

type IncidentUpdate struct {
	ID         uuid.UUID  `json:"id"`
	IncidentID uuid.UUID  `json:"incident_id"`
	Status     string     `json:"status"`
	Message    string     `json:"message"`
	IsPublic   bool       `json:"is_public"`
	AuthorID   *uuid.UUID `json:"author_id,omitempty"`
	CreatedAt  time.Time  `json:"created_at"`
}
