package repository

import (
	"context"
	"time"

	"github.com/bolaabanjo/statuskeet/internal/database"
	"github.com/bolaabanjo/statuskeet/internal/models"
	"github.com/google/uuid"
)

type IncidentRepo struct {
	db database.Querier
}

func NewIncidentRepo(db database.Querier) *IncidentRepo {
	return &IncidentRepo{db: db}
}

func (r *IncidentRepo) Create(ctx context.Context, inc *models.Incident) (*models.Incident, error) {
	result := &models.Incident{}
	err := r.db.QueryRow(ctx,
		`INSERT INTO incidents (org_id, title, status, severity, auto_generated, started_at)
		 VALUES ($1, $2, $3, $4, $5, $6)
		 RETURNING id, org_id, title, status, severity, auto_generated, started_at, resolved_at, created_at, updated_at`,
		inc.OrgID, inc.Title, inc.Status, inc.Severity, inc.AutoGenerated, inc.StartedAt,
	).Scan(
		&result.ID, &result.OrgID, &result.Title, &result.Status, &result.Severity,
		&result.AutoGenerated, &result.StartedAt, &result.ResolvedAt, &result.CreatedAt, &result.UpdatedAt,
	)
	if err != nil {
		return nil, err
	}
	return result, nil
}

func (r *IncidentRepo) LinkService(ctx context.Context, incidentID, serviceID uuid.UUID) error {
	_, err := r.db.Exec(ctx,
		`INSERT INTO incident_services (incident_id, service_id) VALUES ($1, $2) ON CONFLICT DO NOTHING`,
		incidentID, serviceID,
	)
	return err
}

func (r *IncidentRepo) AddUpdate(ctx context.Context, upd *models.IncidentUpdate) (*models.IncidentUpdate, error) {
	result := &models.IncidentUpdate{}
	err := r.db.QueryRow(ctx,
		`INSERT INTO incident_updates (incident_id, status, message, is_public, author_id)
		 VALUES ($1, $2, $3, $4, $5)
		 RETURNING id, incident_id, status, message, is_public, author_id, created_at`,
		upd.IncidentID, upd.Status, upd.Message, upd.IsPublic, upd.AuthorID,
	).Scan(
		&result.ID, &result.IncidentID, &result.Status, &result.Message,
		&result.IsPublic, &result.AuthorID, &result.CreatedAt,
	)
	if err != nil {
		return nil, err
	}
	return result, nil
}

func (r *IncidentRepo) Resolve(ctx context.Context, id uuid.UUID) error {
	now := time.Now()
	_, err := r.db.Exec(ctx,
		`UPDATE incidents SET status = 'resolved', resolved_at = $1, updated_at = $1 WHERE id = $2`,
		now, id,
	)
	return err
}

func (r *IncidentRepo) UpdateStatus(ctx context.Context, id uuid.UUID, status string) error {
	_, err := r.db.Exec(ctx,
		`UPDATE incidents SET status = $1, updated_at = now() WHERE id = $2`,
		status, id,
	)
	return err
}

// GetActiveForService returns the most recent unresolved auto-generated incident
// that affects the given service.
func (r *IncidentRepo) GetActiveForService(ctx context.Context, serviceID uuid.UUID) (*models.Incident, error) {
	inc := &models.Incident{}
	err := r.db.QueryRow(ctx,
		`SELECT i.id, i.org_id, i.title, i.status, i.severity, i.auto_generated,
		        i.started_at, i.resolved_at, i.created_at, i.updated_at
		 FROM incidents i
		 JOIN incident_services s ON s.incident_id = i.id
		 WHERE s.service_id = $1 AND i.status != 'resolved' AND i.auto_generated = TRUE
		 ORDER BY i.started_at DESC LIMIT 1`,
		serviceID,
	).Scan(
		&inc.ID, &inc.OrgID, &inc.Title, &inc.Status, &inc.Severity,
		&inc.AutoGenerated, &inc.StartedAt, &inc.ResolvedAt, &inc.CreatedAt, &inc.UpdatedAt,
	)
	if err != nil {
		return nil, err
	}
	return inc, nil
}

func (r *IncidentRepo) GetByOrgID(ctx context.Context, orgID uuid.UUID, includeResolved bool) ([]models.Incident, error) {
	query := `SELECT id, org_id, title, status, severity, auto_generated, started_at, resolved_at, created_at, updated_at
		 FROM incidents WHERE org_id = $1`
	if !includeResolved {
		query += ` AND status != 'resolved'`
	}
	query += ` ORDER BY started_at DESC`

	rows, err := r.db.Query(ctx, query, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var incidents []models.Incident
	for rows.Next() {
		var inc models.Incident
		if err := rows.Scan(
			&inc.ID, &inc.OrgID, &inc.Title, &inc.Status, &inc.Severity,
			&inc.AutoGenerated, &inc.StartedAt, &inc.ResolvedAt, &inc.CreatedAt, &inc.UpdatedAt,
		); err != nil {
			return nil, err
		}
		incidents = append(incidents, inc)
	}
	return incidents, rows.Err()
}

func (r *IncidentRepo) GetUpdates(ctx context.Context, incidentID uuid.UUID) ([]models.IncidentUpdate, error) {
	rows, err := r.db.Query(ctx,
		`SELECT id, incident_id, status, message, is_public, author_id, created_at
		 FROM incident_updates WHERE incident_id = $1 ORDER BY created_at DESC`,
		incidentID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var updates []models.IncidentUpdate
	for rows.Next() {
		var u models.IncidentUpdate
		if err := rows.Scan(&u.ID, &u.IncidentID, &u.Status, &u.Message, &u.IsPublic, &u.AuthorID, &u.CreatedAt); err != nil {
			return nil, err
		}
		updates = append(updates, u)
	}
	return updates, rows.Err()
}
