package service

import (
	"context"
	"fmt"
	"log/slog"
	"time"

	"github.com/jackc/pgx/v5"

	"github.com/bolaabanjo/statuskeet/internal/models"
	"github.com/bolaabanjo/statuskeet/internal/repository"
)

type IncidentManager struct {
	incidentRepo *repository.IncidentRepo
}

func NewIncidentManager(incidentRepo *repository.IncidentRepo) *IncidentManager {
	return &IncidentManager{incidentRepo: incidentRepo}
}

// ProcessTransitions handles status transitions by creating or resolving incidents.
func (m *IncidentManager) ProcessTransitions(ctx context.Context, transitions []StatusTransition) {
	for _, t := range transitions {
		if t.NewStatus == "operational" {
			m.handleRecovery(ctx, t)
		} else if isIncidentStatus(t.NewStatus) {
			m.handleFailure(ctx, t)
		}
	}
}

func (m *IncidentManager) handleFailure(ctx context.Context, t StatusTransition) {
	// Check if there's already an active incident for this service
	existing, err := m.incidentRepo.GetActiveForService(ctx, t.Service.ID)
	if err != nil && err != pgx.ErrNoRows {
		slog.Error("failed to check active incident", "service", t.Service.Name, "error", err)
		return
	}

	if existing != nil {
		// Active incident exists — update severity if it escalated
		newSeverity := severityFromStatus(t.NewStatus)
		oldSeverity := existing.Severity
		if severityRank(newSeverity) > severityRank(oldSeverity) {
			msg := fmt.Sprintf("Severity escalated: %s is now experiencing %s (was %s)",
				t.Service.Name, humanStatus(t.NewStatus), humanStatus(t.OldStatus))

			_, err := m.incidentRepo.AddUpdate(ctx, &models.IncidentUpdate{
				IncidentID: existing.ID,
				Status:     existing.Status,
				Message:    msg,
				IsPublic:   true,
			})
			if err != nil {
				slog.Error("failed to add incident update", "error", err)
			}

			slog.Info("incident escalated",
				"incident_id", existing.ID,
				"service", t.Service.Name,
				"severity", newSeverity,
			)
		}
		return
	}

	// Create a new incident
	severity := severityFromStatus(t.NewStatus)
	title := fmt.Sprintf("%s: %s", t.Service.Name, humanStatus(t.NewStatus))

	incident, err := m.incidentRepo.Create(ctx, &models.Incident{
		OrgID:         t.Service.OrgID,
		Title:         title,
		Status:        "detected",
		Severity:      severity,
		AutoGenerated: true,
		StartedAt:     time.Now(),
	})
	if err != nil {
		slog.Error("failed to create incident", "service", t.Service.Name, "error", err)
		return
	}

	if err := m.incidentRepo.LinkService(ctx, incident.ID, t.Service.ID); err != nil {
		slog.Error("failed to link service to incident", "error", err)
		return
	}

	msg := fmt.Sprintf("Automated detection: %s transitioned from %s to %s",
		t.Service.Name, humanStatus(t.OldStatus), humanStatus(t.NewStatus))

	_, err = m.incidentRepo.AddUpdate(ctx, &models.IncidentUpdate{
		IncidentID: incident.ID,
		Status:     "detected",
		Message:    msg,
		IsPublic:   true,
	})
	if err != nil {
		slog.Error("failed to add incident update", "error", err)
	}

	slog.Info("incident created",
		"incident_id", incident.ID,
		"service", t.Service.Name,
		"severity", severity,
		"status", t.NewStatus,
	)
}

func (m *IncidentManager) handleRecovery(ctx context.Context, t StatusTransition) {
	existing, err := m.incidentRepo.GetActiveForService(ctx, t.Service.ID)
	if err != nil {
		if err == pgx.ErrNoRows {
			return // No active incident to resolve
		}
		slog.Error("failed to check active incident for recovery", "service", t.Service.Name, "error", err)
		return
	}

	// Resolve the incident
	if err := m.incidentRepo.Resolve(ctx, existing.ID); err != nil {
		slog.Error("failed to resolve incident", "incident_id", existing.ID, "error", err)
		return
	}

	msg := fmt.Sprintf("Automated resolution: %s has recovered and is now operational", t.Service.Name)

	_, err = m.incidentRepo.AddUpdate(ctx, &models.IncidentUpdate{
		IncidentID: existing.ID,
		Status:     "resolved",
		Message:    msg,
		IsPublic:   true,
	})
	if err != nil {
		slog.Error("failed to add resolution update", "error", err)
	}

	slog.Info("incident resolved",
		"incident_id", existing.ID,
		"service", t.Service.Name,
	)
}

func isIncidentStatus(status string) bool {
	return status == "degraded" || status == "partial_outage" || status == "major_outage"
}

func severityFromStatus(status string) string {
	switch status {
	case "major_outage":
		return "critical"
	case "partial_outage":
		return "major"
	default:
		return "minor"
	}
}

func severityRank(severity string) int {
	switch severity {
	case "critical":
		return 3
	case "major":
		return 2
	case "minor":
		return 1
	default:
		return 0
	}
}

func humanStatus(status string) string {
	switch status {
	case "operational":
		return "Operational"
	case "degraded":
		return "Degraded Performance"
	case "partial_outage":
		return "Partial Outage"
	case "major_outage":
		return "Major Outage"
	case "unknown":
		return "Unknown"
	default:
		return status
	}
}
